site_dir: server/docs
site_name: ntfy
site_url: https://ntfy.sh
site_description: Send push notifications to your phone via PUT/POST
copyright: Made with ‚ù§Ô∏è by Philipp C. Heckel
repo_name: binwiederhier/ntfy
repo_url: https://github.com/binwiederhier/ntfy
edit_uri: blob/main/docs/

theme:
  name: material
  language: en
  logo: static/img/ntfy.png
  favicon: static/img/favicon.png
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.sections
    - toc.integrate
    - content.tabs.link
extra:
  homepage: /
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/binwiederhier
extra_javascript:
  - static/js/extra.js
extra_css:
  - static/css/extra.css

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - minify:
      minify_html: true

nav:
- "Getting started": index.md
- "Publishing":
  - "Sending messages": publish.md
- "Subscribing":
  - "From your phone": subscribe/phone.md
  - "From the Web UI": subscribe/web.md
  - "From the CLI": subscribe/cli.md
  - "Using the API": subscribe/api.md
- "Self-hosting":
  - "Installation": install.md
  - "Configuration": config.md
- "Other things":
  - "FAQs": faq.md
  - "Examples": examples.md
  - "Integrations + projects": integrations.md
  - "Release notes": releases.md
  - "Emojis ü•≥ üéâ": emojis.md
  - "Known issues": known-issues.md
  - "Deprecation notices": deprecations.md
  - "Development": develop.md
  - "Privacy policy": privacy.md


