name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      -
        name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install dependencies
        run: make build-deps-ubuntu
      -
        name: Build all the things
        run: make build
      -
        name: Print build results and checksums
        run: make cli-build-results
